M48
; DRILL file {KiCad 8.0.1} date 2024-06-06T12:40:04+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-06T12:40:04+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X-30.2Y2.762
X-30.2Y-2.238
T2
X-15.227Y-15.26
X15.773Y15.74
M30
